on: [push]
name: Build
jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cargo-args: ["--release"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.cargo-args }}